### ISSUE TITLE
Issue with installing Podman Companion for Desktop on Mac 

### ISSUE THREAD

**Issue by rubayatk-tech** [iongion/podman-desktop-companion#51]
After downloading dmg package of the Podman companion for desktop for Mac, I received the following message from Apple 
<img width="259" alt="Screen Shot 2022-04-22 at 10 14 58 AM" src="https://user-images.githubusercontent.com/23279879/164745903-7f1b4d6e-1807-4aae-a346-cee307fb0c8e.png">

Has anyone encountered the same problem, what changes are required in order to get Podman Desktop to work on Mac

**Comment by jsanta** [comment]
Hi. This will happen with many non-appstore apps in Macs, not just Podman Desktop Companion.
Just after getting that message, go to System Preferences -> Security & Privacy -> General (1rst tab)
There you should see which app is not being allowed to run. Click the padlock to make changes, and then allow the app.
Hope it helps.

**Comment by iongion** [comment]
Sorry @rubayatk-tech and thank you so much @jsanta for the help - I hope this will be dealt soon, once the Apple developer situation improves https://github.com/iongion/podman-desktop-companion/issues/24

This is due to requirement from Apple to digitally sign applications, but for that an Apple Developer account is needed, it requires payed subscription which I don't have for now, I have an intel macbook from 2013 where I develop and test all Apple related scenarios. I do rely on feedback from users to know how things are standing which I invaluably received.

**Comment by avsthiago** [comment]
I was still having the same issue after following the steps proposed by @jsanta. What solved for me was to run:

```bash
xattr -d com.apple.quarantine /Applications/Podman\ Desktop\ Companion.app
```

**Comment by rishabhj1717** [comment]
@avsthiago Thank you, this helped 🙌

**Comment by iongion** [comment]
I am closing this because I have no resources to support code-signing, but I mention @avsthiago mitigation in <https://github.com/iongion/podman-desktop-companion/blob/main/USAGE.md>
