### ISSUE TITLE
UI freezes and cannot get back to configuration menu

### ISSUE THREAD

**Issue by v1k0d3n** [iongion/podman-desktop-companion#56]
M1/Apple Silicon
macOS Monterey (12.3.1)
PDC: Version 4.0.3-rc.5 (4.0.3-rc.5)
Podman Version 4.0.3 (using homebrew install method)

Seems like when I try to run a `podman machine init/start` and define the machine in the UI, the UI blanks out and I cannot get the screen to clear or go back to the configuration options screen. 

There's no feedback on what the user should do. Any ideas what I could be doing wrong?

![image](https://user-images.githubusercontent.com/7780945/166478011-2461d682-e44e-4be4-a799-47e3833b0863.png)

**Comment by peterclauterbach** [comment]
On a related note, if the podman machine is missing, and the "Automatically start the API" flag is set, you get the same blank screen, with no indication of what the problem is, or how to recover.

1. Start Podman Desktop Companion
2. User Settings > Startup > Automatically start the API.
3. Quit PDC
4. Stop the podman machine
5. Delete the podman machine.
6. Launch PDC again, you are greeted with the same blank screen, and no way to know what's going on.

recreating and restarting the podman machine gets you back in a state where the UI is visible.
Expectation, if something is not configured or missing, guide the user to what's wrong, and perhaps how to fix it.

**Comment by iongion** [comment]
You are right, I am working on a complete architectural change on how connections are made and how the users are informed.

https://github.com/iongion/podman-desktop-companion/blob/support-custom-wsl-distribution/packages/%40podman-desktop-companion/container-client/README.md

**Comment by iongion** [comment]
Solved in https://github.com/iongion/podman-desktop-companion/releases/edit/4.1.0-rc.21 - re-open if not the case
