### ISSUE TITLE
Unable to connect to poadman machine 

### ISSUE THREAD

**Issue by koolkarni** [iongion/podman-desktop-companion#97]
![2022-06-09_15-21-27](https://user-images.githubusercontent.com/16875126/172955697-d2ad2e63-e0ed-4f0b-b663-aa06d02a6959.png)

**Comment by koolkarni** [comment]
what should be the connection string ? and how to find the location of the required machine ?

**Comment by iongion** [comment]
Hi, in your case on a mac it should be this

https://github.com/iongion/podman-desktop-companion/blob/main/packages/%40podman-desktop-companion/container-client/src/adapters/podman.js#L162

Can you enter this command and paste back the output ?

```podman machine list --format json```

I suspect something is affecting the JSON output due to the error you shown above, you can also put it on `DEBUG` logging and change in the log output right panel from `Default levels` drop down, to include all

![image](https://user-images.githubusercontent.com/867609/172999040-37928cd2-6746-4dc1-94c7-d1e0cbd5c112.png)

**Comment by uncleguanghui** [comment]
I had the same problem.

![screenshot-20220830-171533](https://user-images.githubusercontent.com/29686774/187399014-1dfd74df-3b84-4c50-bd6b-dc8b756348b3.png)

**Comment by iongion** [comment]
Solved in current main - upcoming release soon
